### ISSUE TITLE
url_for using &amp; as separator

### ISSUE THREAD

**Issue by neochrome** [sofadesign/limonade#14]
Hi,
First - thanks for making this great piece of code publicly available.

I've had some issues with the generated url from redirect_to(), which uses url_for().
The problem seems to be that \&amp; and not & is used as separator in the query string as per: https://github.com/sofadesign/limonade/blob/master/lib/limonade.php#L1651

When changing that row to use a plain & it seems to work just fine.
I guess there's a reason for this being \&amp; instead of &, and it's probably me that is doing something wrong - but I thought I should at least ask :)

Cheers,
Johan

**Comment by 16** [comment]
Solved: https://sofadesign.lighthouseapp.com/projects/29612/tickets/49-redirect_to-using-amp-instead-of
