### ISSUE TITLE
route handler fire twice

### ISSUE THREAD

**Issue by andrelec1** [sofadesign/limonade#49]
I use limonade with idiorm ( orm ) 

i have this route : 

    dispatch('/**', function(){
         $uid = params(0); 
        $data = appPloof::AntiSpam($_SERVER["REMOTE_ADDR"]);
        return $data;
    });

and this is the AntiSpam function 

    public static function AntiSpam($ip){
        $ipM = ORM::for_table('antispam')->where_like("ip", $ip)->find_one();
        if(!$ipM){
            $ipM = ORM::for_table('antispam')->create();
            $ipM->ip = $ip;
            $ipM->nb = 0;
            $ipM->save();
            return true;
        }
        else {
            if($ipM->nb < appPloof::$limiteAntiSpam){
                $ipM->set_expr('nb', 'nb + 1');
                $ipM->save();
                return true;
            }
        }
        return false;
    }

in my bdd i can see the nb is incremeted two by two !

**Comment by 16** [comment]
Your route matches every url. I don't know how is designed your application, but you should check how many http requests are made when you are doing a request. Logging the uri before calling your AntiSpam function might be helpful.

**Comment by andrelec1** [comment]
hoo thank ... i just see chrome ( and other navigateur ) check "/favico.ico" by default -_-" !

**Comment by 16** [comment]
;-)
