### ISSUE TITLE
Middleware for router

### ISSUE THREAD

**Issue by rishantagarwal** [sofadesign/limonade#51]
Hi, 

I wanted to implement SEO friendly URL's in my project and was wondering if there is a way using which I could create a middleware to map URL's to controllers dynamically. 

TIA

**Comment by 16** [comment]
Hello,

For SEO friendly URL's, you can use your desired [routing](https://github.com/sofadesign/limonade#routes) with [URL rewriting](https://github.com/sofadesign/limonade#url-rewriting).
