### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by skayo** [sofadesign/limonade#53]
Hello Fabrice,
I wanted to ask if this awesome project is still maintained and being worked on. The last commit was in 2015. 2 years ago....
There are still lots of todos that are not done yet. The current version is 0.5.1 and there are todos until version 1.0!!!
If there is nobody who is currently working on new features, maybe I can overtake the project?
**Short info about me:** I'm 15 years old, from Austria, and have about two and a half years of experience in PHP. I have never maintained such a large project and am a bit unexperienced in it.

If you have any questions, just ask!
I would be very happy if I could overtake and maintain this awesome project!

Well... I hope that anyone replies!
~ Skayo

**Comment by 16** [comment]
Hello Skayo,

I'm happy that you like Limonade ;-) 
And yes, you're welcome if you want to make it go further !
I'll try to help you as I can, depending of my free time. Let me know how you want to handle the project.

++ Fabrice

**Comment by Skayo** [comment]
Awesome! Can you [set me as a collaborator](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/) so I can get access to this repo?

Thanks in advance,
Skayo

**Comment by evnix** [comment]
This would be awesome!
@Skayo It would be really great if you could maintain backward compatibility as you develop it further or at least have compatible looking interfaces so that refactoring isn't too difficult.

I have been using this framework for more than 4 years now on a quite a big product.
Every part of the application has been ripped apart and re-written except for Limonade.
Says something about how robust and reliable Limonade is!! 🥇

**Comment by Skayo** [comment]
@16 Still no access to this repo... Can you set me as a Collaborator please?

I really want to start working on it!

**Comment by Yelles** [comment]
is this project still maintained? it's sad not to see it evolve anymore it was often useful to me

**Comment by Skayo** [comment]
@Yelles 
There's (Fresh Squeezed Limonade)[https://github.com/yesinteractive/fsl] but I haven't tried it

**Comment by Yelles** [comment]
> @Yelles
> There's [Fresh Squeezed Limonade](https://github.com/yesinteractive/fsl) but I haven't tried it

Thanks !

**Comment by justinemailone** [comment]
If this is no longer being maintained maybe we should let others know in the readme and provide a reference link to [Fresh Squeezed Limonade](https://github.com/yesinteractive/fsl) and/or other alternatives.
