### ISSUE TITLE
Multiple directory for includes

### ISSUE THREAD

**Issue by asakurayoh** [sofadesign/limonade#7]
Could be useful to be able to add more include folder for controllers, views, lib, etc.
Use case: Multiple apps (with multiple frontend controller (index.php...)) could load only the code it need + generic code (like, an app with the same layout as an other). 
With this, it could be more simpler to share code between apps, too.

by exemple:

option('views_dir', dirname(__FILE__).'/views');

can become:

option('views_dir', array(dirname(__FILE__).'/views', dirname(__FILE__).'/myapp/views'));

here, /views is my genereic views folder, and /myapp/views is my app folder.

Thanks.

**Comment by 16** [comment]
I have made apps separting front and back in different folders and I didn't feel the need to implement this.
